config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :spots, only: [:index, :show] do
    resources :reviews, only: [:new, :create]
    resources :bookmarks, only: [:create]
    resources :favourites, only: [:create]
    resources :visits, only: [:create]
    collection do
      get :randomise
      get :search
    end
  end

  resources :bookmarks, only: [:index, :update, :destroy]
  resources :favourites, only: [:index, :update, :destroy]
  resources :visits, only: [:index, :destroy]
  resources :users, only: [:index, :show]

end

app/models/spot.rb
class Spot < ApplicationRecord
  has_many :reviews
  has_many :favourites
  has_many :bookmarks
  has_many :visits
  has_many_attached :photos
  has_one_attached :picture
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def time_difference
    a = Time.now.to_i
    b = "#{Date.today} #{sun_end}".to_datetime.to_i

    @times = []
    time = a
    if a < b
      @times << time
      time += 1800
    end

    difference_hours = (b - a) / 3600
    difference_minutes = ((b - a) - (difference_hours * 3600) > 1800) ? ",5" : ""
    if difference_hours > 0
      {
        hour: difference_hours,
        minutes: difference_minutes
      }
    else
      {
        hour: 0,
        minutes: 0
      }
    end
  end
end

app/controllers/spots_controller.rb
require 'csv'
require 'date'
# require 'pycall/import'
# include PyCall::Import

class SpotsController < ApplicationController

require 'time'

  def index
    @spots = Spot.all
    @markers = @spots.geocoded.map do |spot|
      {
        lat: spot.latitude,
        lng: spot.longitude,
        info_window: render_to_string(partial: "info_window", locals: { spot: spot }),
        image_url: helpers.asset_url('map-marker-alt-solid.svg')
      }
    end

    if params[:query].present?
      search
      @spot = Spot.where(select2: params[:query])
      # redirect_to spot_visits_path(@spot)
    else
      @spot = Spot.all
    end
  end


  def show
    @spot = Spot.find(params[:id])
    @review = Review.new

    if @spot.geocoded?

    @markers =
      [{
        lat: @spot.latitude,
        lng: @spot.longitude,
        image_url: helpers.asset_url('map-marker-alt-solid.svg')
      }]
    end
    @bookmark = Bookmark.new
    @favourite = Favourite.new
    @visit = Visit.new



#here comes logic related to backend python sun calculations
    csv_options = { col_sep: ',', force_quotes: true, quote_char: '"' }

# input/output-file python
    filepath = 'lib/assets/python/user_data.csv'

    # a = Time.now.to_i
    # b = "#{Date.today} 21:59".to_datetime.to_i
    # # b = Time.now.to_i
    # @times = []
    # time = a

    # while time <= b do
    #   @times << (time - a) / 60
    #   time += 1800
    # end
    # @sunny_times = []
    # # CSV.open('lib/assets/python/user_data.csv', 'w') do |csv|
    # # headers = ['user_lat', 'user_long', 'when_days', 'when_hours', 'when_minutes', 'sun_shine']
    # # csv << headers
    #   @times.each do |row|
    #     CSV.open('lib/assets/python/user_data.csv', 'w') do |csv|
    #     csv << [@spot.latitude, @spot.longitude, "0", "0", row, "unknown"]
    #     # csv << [@spot.latitude, @spot.longitude, "0", "0", row, "unknown"]
    #     end
    #     `python lib/assets/python/sun_visibility.py`
    #     CSV.foreach(filepath) do |row|
    #       @sunny_times << row[5]
    #     end
    #   end
    # p @sunny_times
    # end

    # `python lib/assets/python/sun_visibility.py`

# output from python
    # @sunny_times = []
    # CSV.foreach(filepath) do |row|
    #   @sunny_times << row[5]
    # end

    #@sunny_from_index = @sunny_times.index { |s| s == 'True' }
    #@sunny_until_index = @sunny_times.index { |s| s == 'True' }
#converts the position in the array to a datetime
    #@sunny_from_datetime = Time.at((Time.now.to_i + (1800 * @sunny_from_index))) if @sunny_from_index != nil
    #@sunny_until_datetime = Time.at((Time.now.to_i + (1800 * @sunny_until_index))) if @sunny_until_index != nil
    #@spot.sun_start = @sunny_from_datetime.strftime("%H:%M") if @sunny_from_index != nil
    #@spot.sun_end = @sunny_until_datetime.strftime("%H:%M") if @sunny_until_index != nil
    #@spot.save
    #raise
  end



  # def randomise
  #   @spot ||= Spot.all.shuffle
  #   @spot.pop
  # end

    def randomise
     @spot = Spot.all.select{|spot|spot.name.length < 10}.sample

     redirect_to spot_path(@spot)
   end

  def search
    @spot = Spot.find(params[:query])
    redirect_to spot_path(@spot)
   end



  private

  def visit_params
    params.require(:visit).permit(:spot_id)
  endmap { |e|  }
  end
end

app/views/spots/_info_window.html.erb
<div class="marker">
  <h2 class="map-spot-name"><%= spot.name %></h2>
  <div class="sun-hours-map d-flex justify-content-center">
    <p class="map-spot-sun-hours" style="font-weight: 100;"><%= spot.time_difference[:hour] %><%= spot.time_difference[:minutes] %>h of sun</p>
  </div>
</div>

app/views/spots/_time_left.html.erb
require 'time'

<% a = Time.now %>
raise
<% b = @spot.sun_end %>

<%= time_difference(a, b) %>

app/views/spots/index.html.erb
<div class="container">
  <body class="index-body">
  </body>

  <div>
    <!-- <h2 class="index-header d-flex justify-content-start pl-3 pt-4 mb-0">Choose a sunny spot</h2> -->
    <%= image_tag "LogoMakr-7pIBgM.png", class: "logo-index" %>
  </div>

  <div class="container mt-2" style="margin-bottom: 80px;">
    <div class="row">
      <div class="col-sm-8 offset-sm-2">
         <a class="btn-navy-index mb-0 d-flex justify-content-center mt-6" href="/spots/randomise" style="font-size: 16px; width: 84%">Can't decide?</a>

        <div
          id="map"
          style="width: 100%; height: 22vh; border-radius: 8px; color: black; margin-top: 18px; box-shadow: 0px 4px 13px -1px #d3d4da;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
          data-center="[18.072545, 59.313682]"
          data-zoom="11">
        </div>

          <div class="spot-index-cards justify-content-between grid-container ">
            <% @spots.each do |spot| %>
              <%= link_to spot_path(spot) do %>
              <div class="spot-index-card container grid-container mr-3 mt-3">
                <h3 class="mb-0 pt-3"><%= spot.name %></h3>



                <div class="d-flex justify-content-evenly justify-content-between mt-2">
                  <div class="spot-index-img h-100">
                    <%= cl_image_tag spot.photos.first.key, crop: :fit if spot.photos.attached? %>
                  </div>
                  <div class="spot-index-infos flex-column justify-content-center h-100 w-100 pb-0 ml-3">
                    <div class="spot-index-details">
<!--
 -->
                  <div class="sun-hours d-flex justify-content-center">
                    <span class="sun-index-icon">&#9788;</span>
                    <p class="sun-hours-index"><%= spot.time_difference[:hour] %><%= spot.time_difference[:minutes] %>h of sun</p>
                  </div>

                     <div class="description-index">
                      <p> <%= spot.description.first(71) + "..." if spot.description %></p>
                    </div>

                      <div class="stars-index d-flex justify-content-center">
                        <% spot.rating.to_i.times do %>
                          <i class="fas fa-star "></i>
                        <% end %>
                        <%(5 - spot.rating.to_i).times do %>
                         <i class="far fa-star"></i>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/spots/randomise.html.erb
 <%#= link_to @spot.random, link_to_spot(@spot) %>

<div>The cafe with the yummy sun suggest for you :) </div>
<body class="show-body" style="background-color: #F5FCFF; color: black;">
        <p>Random Generator</p>
  <div class="nav-top-container navbar-top mt-3">
    <%= link_to "/users", class: "avatar-bordered" do %>
          <% if user_signed_in? %>
          <%= cl_image_tag current_user.user_picture, class:"avatar-img" %>
          <% end %>
    <% end %>
  </div>
</body>

<div class="container mt-2">
  <div class="row">
    <div class="col-sm-8 offset-sm-2">
      <div class="show-name">
        <h1 class="d-flex justify-content-center" style="margin-top: 40px;"> <%=@spot.name %> </h1>
          <p class="d-flex justify-content-center"><%#= @spot.time_difference[:hour] %><%#= @spot.time_difference[:minutes] %>h of remaining sun</p>
         </div>

      <div class="carousel-card">
        <div id="carouselExampleIndicators" class="carousel-slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner">
            <% @spot.photos.each do |photo| %>
            <div class="carousel-item<%= " active" if photo == @spot.photos.first %>">
              <%= cl_image_tag photo.key, class:"d-block w-100", height: "160px" %>
          </div>
            <% end %>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>

app/views/spots/show.html.erb
<%= image_tag "LogoMakr-7pIBgM.png", class: "logo" %>


<body class="show-body" style="background-color: #F5FCFF; color: black;"></body>



<div class="container mt-2">
  <div class="">

    <div class="col-sm-8 offset-sm-2 scrollable">
      <div class="show-name">

        <h1 class="d-flex justify-content-center" style="margin-top: 45px;"> <%= @spot.name %>
        <div class="visits-button">
          <% if Visit.find_by(spot: @spot, user: current_user)%>
            <%= link_to visit_path(Visit.find_by(spot: @spot, user: current_user)), :method => :delete do %>
              <i class="fas fa-plus-square mr-2"></i>
            <% end %>
          <% else %>
            <%= link_to spot_visits_path(@spot), method: :post do %>
              <i class="far fa-plus-square"></i>
            <% end %>
          <% end %>
        </div></h1>
<!--        <p class="d-flex justify-content-center"><#%= @spot.time_difference[:hour] %><#%= @spot.time_difference[:minutes] %>h of remaining sun</p>
 -->  </div>

      <div class="show-details-card">
        <div class="favourite-top">
          <div class="stars-hours">
            <div class="each-rating">
              <% @spot.rating.to_i.times do %>
                <i class="fas fa-star"></i>
              <% end %>
              <% (5 - @spot.rating.to_i).times do %>
                <i class="far fa-star"></i>
              <% end %>
              </div>
              <p class="opening-hours" style="font-weight: 100"><%= @spot.hours %></p>
          </div>
          <div class="bookmark-favourite ratings justify-content-end pt-2">
            <div class="bookmark-button mr-2 mt-2">
              <% if Bookmark.find_by(spot: @spot, user: current_user)%>
                  <%= link_to bookmark_path(Bookmark.find_by(spot: @spot, user: current_user)), :method => :delete do %>
                    <i class="fas fa-bookmark mr-2"></i>
                  <% end %>
              <% else %>
                <%= link_to spot_bookmarks_path(@spot), method: :post do %>
                  <i class="far fa-bookmark"></i>
                <% end %>
              <% end %>
            </div>
            <div class="favourite-button mr-2 mt-2">
              <% if Favourite.find_by(spot: @spot, user: current_user)%>
                <%= link_to favourite_path(Favourite.find_by(spot: @spot, user: current_user)), :method => :delete do %>
                  <i class="fas fa-sun"></i>
                <% end %>
              <% else %>
                <%= link_to spot_favourites_path(@spot), method: :post do %>
                  <i class="far fa-sun"></i>
                <% end %>
              <% end %>
            </div>
          </div>

          </div>
          <div class="d-flex pb-2">
            <div class="picture-item">
              <%= cl_image_tag @spot.photos.first.key, height: "172px" %>
            </div>
            <div class="description-show-container">
              <div class="description-show" style="height: 17vh;">
                <p> <%= @spot.description %> </p>
              </div>
              <div>
                <div class="sun-hours-show d-flex justify-content-center">
                  <span class="sun-show-icon">&#9788;</span>
                  <p style="font-weight: 400; padding-left: 16px; padding-top: 2px;"><%= @spot.time_difference[:hour] %><%= @spot.time_difference[:minutes] %>h</p>
                </div>
                <a class="btn-small-navy mr-1 d-flex justify-content-between" href="/" style="font-size: 11px;"><i class="far fa-calendar-alt"></i></a>
              </div>
            </div>
          </div>
        </div>


      </div>
       <div class="show-map container"
          id="map"
          style="width: 100%; height: 22vh; border-radius: 8px; box-shadow: 0px 4px 13px -1px #d3d4da; padding: 0px; margin-left: 0px"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
          data-zoom="15"
          data-center="[<%= @spot.longitude %>, <%= @spot.latitude %>]">
        </div>

        <div class="review-card">
          <h3 class="d-flex justify-content-center pt-3" style="font-size: 26px;">Add a new review</h3>
              <%= simple_form_for [@spot, @review] do |f| %>
              <%= f.input :rating, collection: (1..5).to_a, label: "Rate your experience:"  %>
              <%= f.input :comment, label: false, :as => :text, :input_html => { :rows => 2 , :style => 'width: 100%'} %>
              <%= f.submit "Submit", class:'btn-navy-form' %>
            <% end %>

        </div>

        <div class="show-review-card">
           <strong class="review-titlte pt-3" style="font-size: 21px;">Reviews</strong>
          <div class="d-flex">
            <div class="stars ratings justify-content-start ml-3 ">
              <div class="review-container">
                <% @spot.reviews.reverse.each do |review| %>
                  <div class="review-row">
                    <div class="author">
                      <div class="avatar-bordered-reviews small" >
                        <% if user_signed_in? %>
                            <%= cl_image_tag review.user.user_picture, class: "avatar-img" %>
                        <% end %>
                      </div>
                      <div class="username-review" style="padding-top: 10px; padding-left: 10px">
                        <%= review.user.username %>
                        <div class="review-rating ">
                          <% review.rating.to_i.times do %>
                            <i class="fas fa-star"></i>
                          <% end %>
                          <% (5 - review.rating.to_i).times do %>
                            <i class="far fa-star"></i>
                          <% end %>
                        </div>
                      </div>

                    </div>
                      <div class="comment-review">
                        "<%= review.comment %>"
                      </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>

    </div>
  </div>
</div>