config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :spots, only: [:index, :show] do
    resources :reviews, only: [:new, :create]
    resources :bookmarks, only: [:create]
    resources :favourites, only: [:create]
    resources :visits, only: [:create]
    collection do
      get :randomise
      get :search
    end
  end

  resources :bookmarks, only: [:index, :update, :destroy]
  resources :favourites, only: [:index, :update, :destroy]
  resources :visits, only: [:index, :destroy]
  resources :users, only: [:index, :show]

end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :spot
  belongs_to :user
  geocoded_by :address
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  def index
    @visits = current_user.visits
    @spots = @visits.map { |visit| visit.spot }
    # @spots.each do |spot|
    @markers = @spots.map do |spot|
      {
        lat: spot.latitude,
        lng: spot.longitude,
        info_window: render_to_string(partial: "spots/info_window", locals: { spot: spot }),
        image_url: helpers.asset_url('map-marker-alt-solid.svg')
      }
    end
  end

  def create
    @spot = Spot.find(params[:spot_id])
    @visit = Visit.new
    @visit.user = current_user
    @visit.spot = @spot
    current_user.intake = 0 unless current_user.intake
    if @visit.save!
      current_user.intake += 2500
      current_user.save!
      redirect_to spot_path(@visit.spot)
    else
      render 'new'
    end
  end

  def destroy
    @visit = Visit.find(params[:id])
    @visit.destroy
    redirect_to spot_path(@visit.spot)
  end

  private

  def visit_params
    params.require(:visit).permit(:spot_id)
  end
end

app/views/visits/index.html.erb
<%= image_tag "LogoMakr-7pIBgM.png", class: "logo" %>

<body class="show-body" style="background-color: #FFFEF9; color: black;"></body>

<div class="container mt-2">
  <div class="row">
    <div class="col-sm-8 offset-sm-2">
      <h3 id="visits" class="d-flex justify-content-center" style="margin-top: 30px; font-size: 33px; color: black;">Visited Spots</h3>

          <div class="spot-index-cards justify-content-between grid-container ">
            <% @spots.each do |spot| %>
              <%= link_to spot_path(spot) do %>
              <div class="spot-index-card container grid-container mr-3 mt-3">
                <h3 class="favourite-name mb-0 pt-3"><%= spot.name %><i class="fas fa-sun sun-favourite ml-1"></i></h3>
                <div class="d-flex justify-content-evenly justify-content-between mt-2">
                  <div class="spot-index-img h-100">
                    <%= cl_image_tag spot.photos.first.key, crop: :fit if spot.photos.attached? %>
                  </div>
                  <div class="spot-index-infos flex-column justify-content-center h-100 w-100 pb-0 ml-3 mt-2">
                    <div class="spot-index-details">

                      <div class="sun-hours d-flex justify-content-center">
                        <span class="sun-index-icon">&#9788;</span>
                        <p style="font-weight:400;"><%= spot.time_difference[:hour] %><%= spot.time_difference[:minutes] %>h of sun</p>
                      </div>

                       <div class="description-index mt-3">
                        <p> <%= spot.description.first(71) + "..." if spot.description %></p>
                        </div>

                          <div class="stars-index d-flex justify-content-center">
                            <% spot.rating.to_i.times do %>
                              <i class="fas fa-star "></i>
                            <% end %>
                            <%(5 - spot.rating.to_i).times do %>
                             <i class="far fa-star"></i>
                            <% end %>
                          </div>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>



       <div class="visit-map">
        <div
          id="map"
          style="width: 100%; height: 21vh; border-radius: 8px;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
          data-center="[18.072545, 59.313682]"
          data-zoom="12">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/visits/show.html.erb
<p><%= @spot.address %></p>
<p><%= @spot.pictures %></p>
<p><%= @spot.sun_start %></p>
<p><%= @spot.sun_end%></p>
<!--  <div>
  <%# if user_signed_in? %>
   <%#= cl_image_tag current_user.user_picture, class:"avatar-img" %>
  <%#end %>
 </div>
 -->
<%= link_to "Back to spots", spots_path  %><br>
<%= link_to "Back to randomise", randomise_spots_path  %><br>
<%= link_to "Back to Home", root_path  %>