config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :spots, only: [:index, :show] do
    resources :reviews, only: [:new, :create]
    resources :bookmarks, only: [:create]
    resources :favourites, only: [:create]
    resources :visits, only: [:create]
    collection do
      get :randomise
      get :search
    end
  end

  resources :bookmarks, only: [:index, :update, :destroy]
  resources :favourites, only: [:index, :update, :destroy]
  resources :visits, only: [:index, :destroy]
  resources :users, only: [:index, :show]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookmarks
  has_many :reviews
  has_many :favourites
  has_many :visits
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :picture


  def user_picture
    if self.picture.attached?
        self.picture.key
    else
      '04s5p8amefgigaoiipqup8r3f7vo'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.all
  end

  def show
  @user = User.find(params[:id])
  @user = Useer.all
  end
end

app/views/users/show.html.erb
<!-- <p id="Profile"><%= Profile  %></p>

<p>
  <strong>Name:</strong>
  <#%= @user.name %>
</p>

<p>
  <strong>email:</strong>
  <#%= @user.email %>
</p> -->

<!-- <p>
  <strong>Reviews</strong>
  <#% @user.reviews.each do |review| %>
  <div>
    <em>"<#%= review.content %>"</em>
    <#%= link_to "Destroy review", review_path(review), method: :delete, data: {confirm: "Are your sure?"}  %>
  </div>
  <#% end %>
</p>

<%#= link_to 'Edit', edit_user_path(@user) %> |
<%#= link_to 'Back', user_path %> -->